# docker-compose.yml

version: "3.8"

services:
  db:
    image: "bitnami/postgresql:14-debian-11"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # network_mode: "host"
volumes:
  postgres: 