# docker-compose.yml

version: "3.8"

services:
  web:
    build: .
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
      - redis

  db:
    image: "bitnami/postgresql:14-debian-11"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      #    restart: unless-stopped
      # env_file:
      #   - .env
  redis:      
    image: "bitnami/redis:6.2"
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


volumes:
  postgres: 